In [1]:
#logistic regression
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
raw_mail_data=pd.read_csv('mail_data.csv')

In [3]:
#replace the null values with null string
mail_data=raw_mail_data.where((pd.notnull(raw_mail_data)),'')

In [4]:
mail_data.head()

  Category                                            Message
0      ham                           Now i'm going for lunch.
1      ham  I'm in school now n i'll be in da lab doing so...
2      ham                       Oh k. . I will come tomorrow
3      ham     Aight, text me tonight and we'll see what's up
4      ham                                               U 2.

In [5]:
#checking the number of rows and columns
mail_data.shape

(6173, 2)

In [6]:
#label encoding spam mail as 0 and ham mail as 1
mail_data.loc[mail_data['Category']=='spam','Category']=0
mail_data.loc[mail_data['Category']=='ham','Category']=1
mail_data.head()

  Category                                            Message
0        1                           Now i'm going for lunch.
1        1  I'm in school now n i'll be in da lab doing so...
2        1                       Oh k. . I will come tomorrow
3        1     Aight, text me tonight and we'll see what's up
4        1                                               U 2.

In [7]:
#seprating the data as text and label
x=mail_data['Message']
y=mail_data['Category']
print(x)

0                                Now i'm going for lunch.
1       I'm in school now n i'll be in da lab doing so...
2                            Oh k. . I will come tomorrow
3          Aight, text me tonight and we'll see what's up
4                                                    U 2.
                              ...
6168    Congrats 2 mobile 3G Videophones R yours. call...
6169                      Ü still got lessons?  Ü in sch?
6170    Y she dun believe leh? I tot i told her it's t...
6171                             Oh did you charge camera
6172    I‘ve got some salt, you can rub it in my open ...
Name: Message, Length: 6173, dtype: object

In [8]:
print(y)

0       1
1       1
2       1
3       1
4       1
       ..
6168    0
6169    1
6170    1
6171    1
6172    1
Name: Category, Length: 6173, dtype: object

In [9]:
#splitting the data into training and test data
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [10]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(6173,)
(4938,)
(1235,)

In [11]:
#feature extraction
#transform test data to numerical values
feature_extraction=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

In [12]:
x_train_features=feature_extraction.fit_transform(x_train)
x_test_features=feature_extraction.transform(x_test)

In [13]:
y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [ ]:
print(x_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34775 stored elements and shape (4457, 7431)>
  Coords	Values
  (0, 2329)	0.38783870336935383
  (0, 3811)	0.34780165336891333
  (0, 2224)	0.413103377943378
  (0, 4456)	0.4168658090846482
  (0, 5413)	0.6198254967574347
  (1, 3811)	0.17419952275504033
  (1, 3046)	0.2503712792613518
  (1, 1991)	0.33036995955537024
  (1, 2956)	0.33036995955537024
  (1, 2758)	0.3226407885943799
  (1, 1839)	0.2784903590561455
  (1, 918)	0.22871581159877646
  (1, 2746)	0.3398297002864083
  (1, 2957)	0.3398297002864083
  (1, 3325)	0.31610586766078863
  (1, 3185)	0.29694482957694585
  (1, 4080)	0.18880584110891163
  (2, 6601)	0.6056811524587518
  (2, 2404)	0.45287711070606745
  (2, 3156)	0.4107239318312698
  (2, 407)	0.509272536051008
  (3, 7414)	0.8100020912469564
  (3, 2870)	0.5864269879324768
  (4, 2870)	0.41872147309323743
  (4, 487)	0.2899118421746198
  :	:
  (4454, 2855)	0.47210665083641806
  (4454, 2246)	0.47210665083641806
  (4455, 4456)	0.24920025316220423
  (4455, 3922)	0.31287563163368587
  (4455, 6916)	0.19636985317119715
  (4455, 4715)	0.30714144758811196
  (4455, 3872)	0.3108911491788658
  (4455, 7113)	0.30536590342067704
  (4455, 6091)	0.23103841516927642
  (4455, 6810)	0.29731757715898277
  (4455, 5646)	0.33545678464631296
  (4455, 2469)	0.35441545511837946
  (4455, 2247)	0.37052851863170466
  (4456, 2870)	0.31523196273113385
  (4456, 5778)	0.16243064490100795
  (4456, 334)	0.2220077711654938
  (4456, 6307)	0.2752760476857975
  (4456, 6249)	0.17573831794959716
  (4456, 7150)	0.3677554681447669
  (4456, 7154)	0.24083218452280053
  (4456, 6028)	0.21034888000987115
  (4456, 5569)	0.4619395404299172
  (4456, 6311)	0.30133182431707617
  (4456, 647)	0.30133182431707617
  (4456, 141)	0.292943737785358

In [18]:
#training the machine learning model
model=LogisticRegression()
model.fit(x_train_features,y_train)

LogisticRegression()

In [15]:
#evaluating the trained model
#prediction on trained data
prediction_on_training_data=model.predict(x_train_features)
accuracy_on_training_data=accuracy_score(y_train,prediction_on_training_data)
print("Accuracy:",accuracy_on_training_data)

Accuracy: 0.9740785743215877

In [16]:
#prediction on test data
prediction_on_test_data=model.predict(x_test_features)
accuracy_on_test_data=accuracy_score(y_test,prediction_on_test_data)
print("Accuracy:",accuracy_on_test_data)

Accuracy: 0.968421052631579

In [19]:
#Building a predictive system
input_mail=["Dear user, your PayPal account is limited. Login now to restore access."]
#convert text to feature vector
input_data_features=feature_extraction.transform(input_mail)
#making prediction
prediction=model.predict(input_data_features)
if prediction[0]==1:
    print("Normal Mail")
else:
    print("Spam Mail")

Normal Mail